services:
  gkmn:
    image: "gokemon-build:latest"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5432:5433"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "gokemon"