services:
  gkmn:
    image: "gokemon-build:latest"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - learning
  db:
    image: "postgres:latest"
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "gokemon"
    networks:
      - learning
networks:
  learning:
    driver: bridge